# Generated by Django 2.1.7 on 2019-03-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='ikea_id',
            field=models.PositiveIntegerField(default=65539),
            preserve_default=False,
        ),
    ]
