# Generated by Django 2.1.7 on 2019-03-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('grid_cost', models.PositiveIntegerField()),
                ('electricity_cost', models.PositiveIntegerField()),
            ],
        ),
    ]
