# Generated by Django 2.1.7 on 2019-03-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricity',
            name='sum',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
