# Generated by Django 2.1.7 on 2019-03-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_electricity_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricity',
            name='sum',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
